### ISSUE TITLE
Instant Apps Roadmap

### ISSUE THREAD

**Issue by OrkoHunter** [felvin-search/instant-apps#126]
**v0: Instant Apps are born. Open Source and can be written by anyone!**

- [x] Apps are React components in a Create React App project
- [x] Apps are Open Source

**v1: Marketplace of apps**

- [ ] Each app is a unique NPM package. Motivation for this below
  - Apps can have better Metadata. Name, Description. Example Queries, Screenshot URL, Author(s), Unique URL for sharing, Search
  - Easy to identity app's dependencies. 
  - It'll be easy to exclude apps with malicious dependencies. (Security, License incompatibility, Very large bundle size, etc.)
  - Apps can be developed outside of this repository. (Private apps can also exist)
- [ ] Felvin Core packages export utility functions, types, Standard UI components.

**v2: More powerful apps with backend when it's needed.**

- [ ] Allow apps to expose a new entrypoint (a backend function) which uses Secrets/API Keys, etc. which queryToData can call.
- [ ] Allow apps to expose functions which can call Linux utilities like ffmpeg, imagemagick ([convert](https://linux.die.net/man/1/convert)) or any other video/audio/image processors.

**Comment by OrkoHunter** [comment]
(Comment in progress)

Few words on v2: Server side rendering of apps - for anyone willing to pick it up

Prerequisites -

* Do make sure you understand how things work a little more depth than create-react-app. You should feel comfortable
  * connecting the dots from A to B where A is the web development of 2005 -> serving an HTML file in a browser with a static JS file included as a script and B is what we do today -> writing modern complex React components, with JSX, CSS in JS, importing images in JS and all the madness.
  * spend a lot of time on bundlers (webpack etc.), what do they do with
