### ISSUE TITLE
Possible Instant apps

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#7]
## General

- [ ] Timezone conversion https://github.com/felvin-search/instant-apps/issues/2
- [ ] Random String generator https://github.com/felvin-search/instant-apps/issues/25
- [ ] Random name generator 
- [x] Currency conversion
- [x] Timer App
- [x] Dictionary App

## Image manipulation
- [ ] Crop image https://github.com/felvin-search/instant-apps/issues/26
- [ ] Resize image https://github.com/felvin-search/instant-apps/issues/27
- [ ] Remove background
- [ ] Invert colors
- [ ] Unit Convertor

## Dev Related
- [ ] Word Count https://github.com/felvin-search/instant-apps/issues/28
- [ ] Unix timestamp to current time https://github.com/felvin-search/instant-apps/issues/29
- [ ] Create markdown table https://github.com/felvin-search/instant-apps/issues/30
- [ ] Yaml Validation https://github.com/felvin-search/instant-apps/issues/31
- [x] JSON formatter

## Games
- [x] Tic Tac Toe https://github.com/felvin-search/instant-apps/pull/18
- [ ] Atari Breakout
- [ ] Pong

**Comment by OrkoHunter** [comment]
- Current time in locations

I often search for

"time in India"
"time in New York"
etc.

**Comment by OrkoHunter** [comment]
"random joke"
"tell me a joke"
"joke"

:)

**Comment by OrkoHunter** [comment]
Each idea should be a separate issue, then it'll be easy to track them, their assignees, etc.

**Comment by OrkoHunter** [comment]
Weather app

"weather"
"temperature"
"weather in <place>"
"temperature in <place>"

**Comment by OrkoHunter** [comment]
Grok the issue template and labels

**Comment by OrkoHunter** [comment]
@felvin-search/maintainers Closing this issue now. Let's create separate issues for each app as discussed.

@hargup I left a few issues unopened and thought it'd be great if you could open them! :)

* random name generator
* image manipulation last 3 things
* two games

**Comment by hargup** [comment]
Done! Created issues

**Comment by OrkoHunter** [comment]
Awesome! 🔥🔥
